name: Check Wakapi Status
on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  check-wakapi-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run status update script
        env:
          STATUSPAGE_API_KEY: ${{ secrets.STATUSPAGE_API_KEY }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
          COMPONENT_ID: ${{ secrets.COMPONENT_ID }}
        run: |
          python status_update.py