name: Service Status Monitoring and Update

# Remove or comment out the schedule section to stop auto execution
# on:
#   schedule:
#     - cron: "*/5 * * * *"  # Runs every 5 minutes
#   workflow_dispatch:
#     inputs:
#       test_mode:
#         description: "Enable test mode to simulate an outage"
#         required: false
#         default: "false"  # String value

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: "Enable test mode to simulate an outage"
        required: false
        default: "false"  # String value

jobs:
  check-service-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run status update script
        env:
          STATUSPAGE_API_KEY: ${{ secrets.STATUSPAGE_API_KEY }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
          TEST_MODE: ${{ github.event.inputs.test_mode }}
        run: |
          python status_update.py