name: Wakatime Metrics
on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  wakatime-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install requests python-dotenv # python-dotenv is needed for update_readme.py 
